version: "3.9"
services:
  ch5_php-apache:
    ports:
      - "8085:80"
    build: './build/php'
  ch5_db:
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: F79kw1ke%4c2
      MYSQL_DATABASE: ch5challenge
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
