version: "3.9"
services:
  ch9_php-apache:
    ports:
      - "8089:80"
    build: './build/php'
  ch9_db:
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 87W1%^xfBuYl
      MYSQL_DATABASE: ch9challenge
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
