version: "3.9"
services:
  home_php-apache:
    ports:
      - "80:80"
    build: './build/php'
  home_db:
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 87W1%^xfBuYl
      MYSQL_DATABASE: challenges
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
