version: "3.9"
services:
  ch7_php-apache:
    ports:
      - "8087:80"
    build: './build/php'
  ch7_db:
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 87W1%^xfBuYl
      MYSQL_DATABASE: ch7challenge
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
